CREATE TABLE articles (
  id INT AUTO_INCREMENT NOT NULL,
  title VARCHAR(255) NOTNULL,
  content LONGTEXT NOT NULL,
  dateAdded DATETIME NOT NULL,
  authorId INT NOT NULL,
  INDEX IDX_BFDD3168A196F9FD (authorId),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE users (
  id INT AUTO_INCREMENT NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  fullName VARCHAR(255) NOT NULL,
  UNIQUE INDEX UNIQ_1483A5E9E7927C74 (email),
  PRIMARY KEY(id)
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

ALTER TABLE articles
  ADD CONSTRAINT FK_BFDD3168A196F9FD
FOREIGN KEY (authorId)
REFERENCES users (id);